### ISSUE TITLE
Replace Wheezer switch-case with Array

### ISSUE THREAD

**Issue by danielathome19** [actes2/actes2.github.io#1]
Rather than chaining conditions, an array would be much better and drastically increase page runtime -- make a list to hold the URLs and randomly select:

```js
let wheezers = [
  "URL1", 
  "URL2", 
  "URL3"
];
carl.src = wheezers[Math.floor(Math.random() * wheezers.length)];
```

**Comment by actes2** [comment]
What a helpful comment, I think that the wheezer switch-case was a shotty implementation and really represents a key-factor to what's wrong with our society.

God-bless I will fix this issue sir.
